
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Button multiplicar;
	private global::Gtk.Button restar;
	private global::Gtk.Button sumar;
	private global::Gtk.Button dividir;
	private global::Gtk.Entry Resultado;
	private global::Gtk.Entry Numero2;
	private global::Gtk.Entry Numero1;
	private global::Gtk.Label numero1;
	private global::Gtk.Label resultado;
	private global::Gtk.Label numero2;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.multiplicar = new global::Gtk.Button ();
		this.multiplicar.CanFocus = true;
		this.multiplicar.Name = "multiplicar";
		this.multiplicar.UseUnderline = true;
		this.multiplicar.Label = global::Mono.Unix.Catalog.GetString ("multiplicar");
		this.fixed1.Add (this.multiplicar);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.multiplicar]));
		w1.X = 183;
		w1.Y = 214;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.restar = new global::Gtk.Button ();
		this.restar.CanFocus = true;
		this.restar.Name = "restar";
		this.restar.UseUnderline = true;
		this.restar.Label = global::Mono.Unix.Catalog.GetString ("restar");
		this.fixed1.Add (this.restar);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.restar]));
		w2.X = 113;
		w2.Y = 214;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.sumar = new global::Gtk.Button ();
		this.sumar.CanFocus = true;
		this.sumar.Name = "sumar";
		this.sumar.UseUnderline = true;
		this.sumar.Label = global::Mono.Unix.Catalog.GetString ("sumar");
		this.fixed1.Add (this.sumar);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.sumar]));
		w3.X = 45;
		w3.Y = 212;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.dividir = new global::Gtk.Button ();
		this.dividir.CanFocus = true;
		this.dividir.Name = "dividir";
		this.dividir.UseUnderline = true;
		this.dividir.Label = global::Mono.Unix.Catalog.GetString ("dividir");
		this.fixed1.Add (this.dividir);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.dividir]));
		w4.X = 277;
		w4.Y = 215;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Resultado = new global::Gtk.Entry ();
		this.Resultado.CanFocus = true;
		this.Resultado.Name = "Resultado";
		this.Resultado.IsEditable = true;
		this.Resultado.InvisibleChar = '●';
		this.fixed1.Add (this.Resultado);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Resultado]));
		w5.X = 116;
		w5.Y = 138;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Numero2 = new global::Gtk.Entry ();
		this.Numero2.CanFocus = true;
		this.Numero2.Name = "Numero2";
		this.Numero2.IsEditable = true;
		this.Numero2.InvisibleChar = '●';
		this.fixed1.Add (this.Numero2);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Numero2]));
		w6.X = 117;
		w6.Y = 84;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Numero1 = new global::Gtk.Entry ();
		this.Numero1.CanFocus = true;
		this.Numero1.Name = "Numero1";
		this.Numero1.IsEditable = true;
		this.Numero1.InvisibleChar = '●';
		this.fixed1.Add (this.Numero1);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Numero1]));
		w7.X = 114;
		w7.Y = 38;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.numero1 = new global::Gtk.Label ();
		this.numero1.Name = "numero1";
		this.numero1.LabelProp = global::Mono.Unix.Catalog.GetString ("numero1");
		this.fixed1.Add (this.numero1);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.numero1]));
		w8.X = 51;
		w8.Y = 39;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.resultado = new global::Gtk.Label ();
		this.resultado.Name = "resultado";
		this.resultado.LabelProp = global::Mono.Unix.Catalog.GetString ("resultado");
		this.fixed1.Add (this.resultado);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.resultado]));
		w9.X = 52;
		w9.Y = 141;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.numero2 = new global::Gtk.Label ();
		this.numero2.Name = "numero2";
		this.numero2.LabelProp = global::Mono.Unix.Catalog.GetString ("numero2");
		this.fixed1.Add (this.numero2);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.numero2]));
		w10.X = 52;
		w10.Y = 91;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.multiplicar.Clicked += new global::System.EventHandler (this.OnMultiplicarClicked);
		this.restar.Clicked += new global::System.EventHandler (this.OnRestarClicked);
		this.sumar.Clicked += new global::System.EventHandler (this.OnSumarClicked);
		this.dividir.Clicked += new global::System.EventHandler (this.OnDividirClicked);
	}
}
